# Generated by Django 3.1 on 2020-08-09 04:46

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', ckeditor.fields.RichTextField()),
                ('feature_image', models.ImageField(upload_to='featured_image')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BloodPacket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packet_num', models.CharField(max_length=50, unique=True)),
                ('expire_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='BloodRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateField()),
                ('amount_of_blood', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BloodType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_type', models.CharField(choices=[('O+', 'O-Positive'), ('O-', 'O-Negative'), ('A+', 'A-Positive'), ('A-', 'A-Negative'), ('B+', 'B-Positive'), ('B-', 'B-Negative'), ('AB+', 'AB-Positive'), ('AB-', 'AB-Negative')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(max_length=200)),
                ('campaign_location', models.CharField(max_length=100)),
                ('campaign_start_date_time', models.DateTimeField()),
                ('campaign_end_date_time', models.DateTimeField()),
                ('campaign_host_name', models.CharField(max_length=200)),
                ('about_campaign', ckeditor.fields.RichTextField()),
                ('campaign_image', models.ImageField(upload_to='campaign_image')),
            ],
        ),
        migrations.CreateModel(
            name='CollectedBlood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collected_date', models.DateField()),
                ('a_positive', models.IntegerField(null=True)),
                ('a_negative', models.IntegerField(null=True)),
                ('o_positive', models.IntegerField(null=True)),
                ('o_negative', models.IntegerField(null=True)),
                ('b_positive', models.IntegerField(null=True)),
                ('b_negative', models.IntegerField(null=True)),
                ('ab_positive', models.IntegerField(null=True)),
                ('ab_negative', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', ckeditor.fields.RichTextField()),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsor_name', models.CharField(max_length=200)),
                ('sponsor_email', models.EmailField(max_length=254, unique=True)),
                ('sponsor_amount', models.FloatField()),
                ('sponsor_type', models.CharField(choices=[('personal', 'personal'), ('organizational', 'organizational')], max_length=14)),
                ('phone_number', models.CharField(max_length=15)),
                ('sponsor_address', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volunteer_name', models.CharField(max_length=100)),
                ('volunteer_address', models.CharField(max_length=100)),
                ('volunteer_mobile_number', models.CharField(max_length=15)),
                ('volunteer_role', models.CharField(max_length=20)),
                ('volunteer_profile_pic', models.ImageField(upload_to='volunteer_profile')),
                ('register_for_campaign', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blood.campaign')),
            ],
        ),
    ]
